### ISSUE TITLE
Error : ConfusionMatrix.__new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by yash-sharma13** [hwang9u/emo-catcher#1]
I was trying to implement the same model using your code and came across this error 
In **notebook/performance-evaluation.ipynb** under **1.2 Create Confusion Matrix** 

**Code :** 
model.eval()
cm_test= create_confusion_matrix(model, test_dloader, n_class=8)

**Error :**  ConfusionMatrix.__new__() missing 1 required positional argument: 'task'

I tried to solve it but nothing worked, please help me resolve it.
![error 1](https://github.com/hwang9u/emo-catcher/assets/95098944/85cbe674-6de8-40a7-b9cb-44a50014d27a)
****

**Comment by hwang9u** [comment]
Hello! Thank you for visiting my repo.
I think it has been changed to specify a `task` argument as `torchmetrics` has been updated.
Therefore, we can change it to `ConfusionMatrix( num_classes=n_class, task='multiclass' )`
(I will update it like that)
You made my repo better!
I hope it was helpful, let's communicate anytime.
Have a nice day wherever you are :)

+) If you have time, plz look around my other repo and leave your comments.
